### ISSUE TITLE
Requirements for a good release

### ISSUE THREAD

**Issue by mixmixmix** [road86/bahis-desk#13]
- [ ] pressing a putton should disable that button (for instance in sign in)
- [ ] when syncing it should block the screen with a loader?
- [ ] make the button turn from red to yellow after a complete sync
- [ ] give a correct time for sync button
- [ ] fix images/logos
- [ ] Add a loading/sync button when waiting for server response
- [ ] speed up synchronisation (https://github.com/road86/bahis-serve/issues/1)

**Comment by ChasNelson1990** [comment]
I am closing this issue as a lot of this is now superseded by other issues, PRs or the use of milestones.
Some of these points might be general style guidelines, e.g. how a button behaves. But I think that might be more important as part of a bahis v3 discussion?
