### ISSUE TITLE
Searching entries ends up with frozen app.

### ISSUE THREAD

**Issue by yokat** [road86/bahis-desk#22]
### Bug Description

A bug happened!
Desktop app freezes when trying to search within the submitted list.

### To Reproduce

1.  Go to 'Clinical' ->'New Patient' -> 'Submitted Data'
2.  Select 'Date of visit' 
3.  Type in Search "15.12.2022"
4.  Press Submit

### Expected Behaviour

The server does not seem to receive any request, so it might be that it is purely a local problem

**Comment by ChasNelson1990** [comment]
@shaarful - is this related to the filtered views freezing too?
