### ISSUE TITLE
Not all data is populated when a new db is initialised

### ISSUE THREAD

**Issue by ChasNelson1990** [road86/bahis-desk#26]
### Bug Description

When using bahis-desk with a new user, e.g. first time install, some of the form drop-down boxes are empty and the db shows no data in those tables. This is solved by running an app sync.

### To Reproduce

1. Log in
2. Open a form
3. Select a drop down box
4. See nothing
5. Run sync, repeat
6. See something

### Expected Behaviour

These tables should be populated on first sign in.

### Additional Context

I think this is due to the formConfigRes fails that occur on every login - the tables exist (though are empty) and so it doesn't populate them.

**Comment by ChasNelson1990** [comment]
This is solved manually by hitting sync

**Comment by ChasNelson1990** [comment]
Closing as the manual solution seems to be fine for v2.2.x

A new issue can be raised if this really becomes a use problem

**Comment by mixmixmix** [comment]
I just want to point out that this is (almost) correct. In the ideal world sync should happen always after login automatically and updates any dropdown lists that might have changed.
