### ISSUE TITLE
After initial login modules screen is blank in 2.0.6-dev

### ISSUE THREAD

**Issue by mixmixmix** [road86/bahis-desk#28]
### Bug Description

in 2.0.6-dev module screen is blank after initial login
![Przechwytywanie](https://user-images.githubusercontent.com/9990867/209542093-e59fac8a-4da3-4b43-b616-4d99a6fb0c2d.PNG)

### To Reproduce

Log in as any user for a first time

### Expected Behaviour

![Przechwy2222tywanie](https://user-images.githubusercontent.com/9990867/209542114-a101900f-b244-45df-97b3-d5d1975c76fc.PNG)

### Additional Context

Logging back in as the same user shows the modules correctly

**Comment by mixmixmix** [comment]
It is on a new db, that's what I mean by "initial login". 
It happened to all the users I tested, `ghatail`, `paba`,`rupsa`

**Comment by ChasNelson1990** [comment]
How long did you wait? Some times it takes a little while for the catchments and modules to load. I have extended the toast time out in my other PR for this exact reason. I also have another fix in my other PR that may contribute to - formConfig now happens at dB creation but module sync at app sync.

**Comment by mixmixmix** [comment]
It never loads.

**Comment by ChasNelson1990** [comment]
Hmm... I can't recreate this?

**Comment by mixmixmix** [comment]
We have established that it cannot be reproduced when running `bahis-serve` locally as the delays of development server might be causing it.

**Comment by ChasNelson1990** [comment]
This should be fixed in the latest commits to #30
