### ISSUE TITLE
Call to module-list has confusing "last_modified" date in 2.0.6-dev

### ISSUE THREAD

**Issue by mixmixmix** [road86/bahis-desk#29]
### Bug Description

When logging in as a new user all queries should have `last_modified` as 0. In the bahis-desk logs it announces the call with `0`, however in server logs I see
<img width="600" alt="Screenshot 2022-12-26 at 12 09 28" src="https://user-images.githubusercontent.com/9990867/209542443-99d81836-a54c-4de8-8026-7f9d72f1b7c1.png">

### To Reproduce

4. See error.

### Expected Behaviour

<img width="548" alt="Screenshot 2022-12-26 at 12 09 12" src="https://user-images.githubusercontent.com/9990867/209542464-8c719243-414a-4708-bba7-7ae4997d91a0.png">

### Additional Context

As long as you actually delete database in 2.0.6-dev on every new user log in I don't understand how it can ba happening.

**Comment by ChasNelson1990** [comment]
Fixed in #30

**Comment by mixmixmix** [comment]
Can you clarify how that was happening?
