### ISSUE TITLE
(discussion) configuration for building/testing

### ISSUE THREAD

**Issue by mixmixmix** [road86/bahis-desk#32]
I wonder if it is possible to set up something akin following ideas:

- you start the app with server specified in enviromental variable, and depending on the server name, different colour scheme is applied
- feature branches are by default connected to localhost, development to dev, and master to production
- when you make a PR to the dev or master branch it automatically sets the colours and changes server names as well as adds a minor revision to version to the name.

@ChasNelson1990 something to think about when we have time.

**Comment by ChasNelson1990** [comment]
This should come from modernising the stack (on going my end) but it's going to be a slow fix so pinning as wontfix for now.

**Comment by ChasNelson1990** [comment]
I am making this a priority for the v2.3.x milestone as I think some work here will really help us
