### ISSUE TITLE
Build Bahis desk for linux

### ISSUE THREAD

**Issue by sharful09** [road86/bahis-desk#62]
### Problem

When bahis-desk is built for Linux it builds perfectly it builds a `.snap` file but whilst trying to install it gives an error `Failed to install file: not supported` and not installing. I test it for ubuntu. @WaliZaman Bhai mention it [here](https://faobdectad.slack.com/archives/C04EKPHLQLF/p1676283166325009)

### Desired Solution

We need to add something to `package.json` file then `.deb` file will be created for ubuntu. I will create a PR for this.

### Additional Context

This time we will do it for Ubuntu. We will do it for other Linux distributions in the next release. Any suggestions would be appreciated.

**Comment by mixmixmix** [comment]
@ChasNelson1990 why are we making a linux build? I don't think we can treat it as the same as windows build, as in, we still need to do testing on the built app on windows.
